### PR TITLE
Add to the word-break property support of the break-word value (CSS3)

### PR DESCRIPTION
**Pull request by agabrys**
[5.2. Breaking Rules for Letters: the word-break property](https://www.w3.org/TR/css-text-3/#word-break-property)

### CODE REVIEW

**Comment by agabrys** [comment]
[Travis #272](https://travis-ci.org/racodond/sonar-css-plugin/builds/377269307) build has failed, because `./travis.sh: line 12: SONAR_TOKEN: unbound variable`.

**Comment by racodond** [comment]
This is "normal" because SonarQube analysis cannot be run on forked branches for security reasons.

**Comment by Ivan-L** [comment]
Hi @racodond,

We're running into this issue now where the `break-word` value is being flagged as invalid for the `word-break` CSS property. I see that this has been fixed as part of the 4.19 milestone however there is no release for version 4.19 on the Releases page for this repo. Do you still intend on including other fixes as part of the 4.19 release?

**Comment by racodond** [comment]
Hi @Ivan-L,

I don't feel like maintaining this plugin anymore. Feel free to fork the repository and release a version on your side.

David

**Comment by Ivan-L** [comment]
Hey @racodond,

I was surprised by your response but then after some research saw what happened. Did SonarSource even consult you before doing what they did? It is not very nice of them at all to use the same key as your plugin. I suppose the discussion is probably not for a public forum.

Please know however, that my team and I really appreciate all of the effort that you put into this plugin. We use it daily and it comments on our PRs all the time. It keeps the folks on our team responsible for CSS/SCSS on their toes, but above all, it has kept our codebase consistent and clean. Thank you for having maintained a really great plugin.

**Comment by racodond** [comment]
Hi @Ivan-L,

Thank you very much for your very kind words!

No, SonarSource didn't consult me at all.

David

**Pull request merged**
